### ISSUE TITLE
懒汉式线程安全写法 存在问题

### ISSUE THREAD

**Issue by shenzhijun** [xurui1995/Sword-pointing-to-offer#1]
b=new B(); 
这句话不是原子操作，存在指令重排序。
正确写法是 b 变量加 volatile

**Comment by xurui1995** [comment]
谢谢指导。马上就改

**Comment by murdonson** [comment]
@shenzhijun   不是用synchronized保证了原子性吗   synchronized既能保证原子性 申请锁 释放锁都会主动刷新线程的内存 也能保证可见性   所以没有必须要加volatile

**Comment by xurui1995** [comment]
> @shenzhijun 不是用synchronized保证了原子性吗 synchronized既能保证原子性 申请锁 释放锁都会主动刷新线程的内存 也能保证可见性 所以没有必须要加volatile

这里加volatile的原因可参考https://monkeysayhi.github.io/2016/11/29/volatile%E5%85%B3%E9%94%AE%E5%AD%97%E7%9A%84%E4%BD%9C%E7%94%A8%E3%80%81%E5%8E%9F%E7%90%86/
